version: '3.3'
services:
  traefik:
    image: traefik:v2.1.1
    ports:
      - 80:80
      - 443:443
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik1.rule=Host(`traefik.localhost`)"
        - traefik.http.services.traefik1.loadbalancer.server.port=8080

      replicas: ${TRAEFIK_REPLICAS:-1}
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
    command:
      - --log.level=INFO
      - --entrypoints.web.address=:80
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode=true
      - --providers.docker.network=traefik-public
      - '--providers.docker.defaultRule=Host(`traefik.localhost`)'
      - --accesslog=true
      - --accessLog.filePath=/var/log/access.log
      - --accessLog.format=json
      - --accesslog.bufferingsize=100
      - --accessLog.fields.names.ClientHost=redact
      - --accessLog.fields.names.BackendAddr=keep
      - --accessLog.fields.names.BackendName=keep
      - --accessLog.fields.names.FrontendName=keep
      - --ping
           
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public


 # Consul Leader configuration     
  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.consul-leader.rule=Host(`consul-leader.localhost`)"
        - "traefik.http.services.consul-leader.loadbalancer.server.port=8500"
        # Traefik service that listens to HTTPS
        #- traefik.http.routers.consul-leader.auth.basic.users=${USERNAME}:${HASHED_PASSWORD}

# configuration for consul replica        
  consul-replica:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - traefik-public
    deploy:
      replicas: ${CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id

volumes:
  consul-data-leader:
  consul-data-replica:

networks:
  traefik-public:
    external: true
